[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = ["python3.12 -m pip install -r requirements.txt"]

[start]
cmd = "python3.12 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

